services:
  exporter:
    build: .
    container_name: exporter
    command: ["/app/exporter", "-port", "2112", "-appid", "PEERINGMON-DEV"]


# peeringmon_controller:
#   image: ghcr.io/peeringtestbed/peeringmon_controller
#   user: "1001"
#   container_name: peeringmon_controller
#   command: ["/peeringmon_controller", "-i", "60"]
#   ports:
#     - 2113:2113
#   networks:
#     - monitoring


  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana


  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
