services:
  peeringmon_exporter:
    image: ghcr.io/peeringtestbed/peeringmon_exporter:latest
    user: "1001" # change this to a nonroot user
    container_name: peeringmon_exporter
    command: ["/peeringmon_exporter", "-appid", "PEERINGMON-DEV"]
    ports:
      - 2112:2112
    networks:
      - monitoring

# peeringmon_controller:
#   image: ghcr.io/peeringtestbed/peeringmon_controller
#   user: "1001"
#   container_name: peeringmon_controller
#   command: ["/peeringmon_controller", "-i", "60"]
#   ports:
#     - 2113:2113
#   networks:
#     - monitoring

  prometheus:
    image: prom/prometheus:latest
    user: "1001"
    container_name: prometheus
    volumes:
      - /srv/dockerdata/promdata:/prometheus
      - /srv/dockerdata/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    user: "1001" # change this to a nonroot user
    container_name: grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
    volumes:
      - /srv/dockerdata/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring

networks:
  monitoring:
